repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.13.0
    hooks:
      - id: pyupgrade
        args: [--py311-plus]

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.291
    hooks:
      - id: ruff