"""

Revision ID: 61fd7ddbb63e
Revises: 26f3f3105e26
Create Date: 2023-11-06 00:31:29.771335

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "61fd7ddbb63e"
down_revision: str | None = "26f3f3105e26"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "auth__refresh_tokens",
        sa.Column("is_revoked", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.create_index(
        op.f("ix_auth__refresh_tokens_is_revoked"),
        "auth__refresh_tokens",
        ["is_revoked"],
        unique=False,
    )
    op.create_unique_constraint(None, "auth__refresh_tokens", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "auth__refresh_tokens", type_="unique")
    op.drop_index(op.f("ix_auth__refresh_tokens_is_revoked"), table_name="auth__refresh_tokens")
    op.drop_column("auth__refresh_tokens", "is_revoked")
    # ### end Alembic commands ###
