"""

Revision ID: 9cd79467a454
Revises: 189247e8ff17
Create Date: 2023-11-19 17:09:40.133754

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from app.core.db import GUID

# revision identifiers, used by Alembic.
revision: str = "9cd79467a454"
down_revision: str | None = "189247e8ff17"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth__email_verifications",
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("verification_code", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("user_id", GUID(), nullable=False),
        sa.Column("usage", sa.String(), nullable=False),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.Column("id", GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user__users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        op.f("ix_auth__email_verifications_is_revoked"),
        "auth__email_verifications",
        ["is_revoked"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_auth__email_verifications_is_revoked"), table_name="auth__email_verifications"
    )
    op.drop_table("auth__email_verifications")
    # ### end Alembic commands ###
