"""

Revision ID: df3b29c30acc
Revises: 61fd7ddbb63e
Create Date: 2023-11-19 22:03:10.239476

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from app.core.db import GUID

# revision identifiers, used by Alembic.
revision: str = "df3b29c30acc"
down_revision: str | None = "61fd7ddbb63e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth__email_verifications",
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("user_id", GUID(), nullable=False),
        sa.Column("usage", sa.String(), nullable=False),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.Column("id", GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user__users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        op.f("ix_auth__email_verifications_email"),
        "auth__email_verifications",
        ["email"],
        unique=False,
    )
    op.create_index(
        op.f("ix_auth__email_verifications_is_revoked"),
        "auth__email_verifications",
        ["is_revoked"],
        unique=False,
    )
    op.add_column(
        "user__users",
        sa.Column("email_verified", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user__users", "email_verified")
    op.drop_index(
        op.f("ix_auth__email_verifications_is_revoked"), table_name="auth__email_verifications"
    )
    op.drop_index(
        op.f("ix_auth__email_verifications_email"), table_name="auth__email_verifications"
    )
    op.drop_table("auth__email_verifications")
    # ### end Alembic commands ###
