"""

Revision ID: c1d1484bf6f3
Revises: b2971d89afb2
Create Date: 2023-12-01 00:29:34.930687

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c1d1484bf6f3"
down_revision: str | None = "b2971d89afb2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("auth__email_verifications", sa.Column("state", sa.String(), nullable=False))
    op.create_unique_constraint(None, "auth__email_verifications", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "auth__email_verifications", type_="unique")
    op.drop_column("auth__email_verifications", "state")
    # ### end Alembic commands ###
